FROM golang:1.12.0-alpine

LABEL vendor="JobTeaser" \
      com.jobteaser.version="1.12.0" \
      com.jobteaser.release-date="2019-03-08" \
      maintainer="dev@jobteaser.com"

RUN apk add --no-cache git make gcc libc-dev pkgconfig librdkafka-dev
