#!/usr/bin/env bash

usage() {
  cat <<EOF
Usage: $0 pod
EOF
}


main() {
  POD_NAME=$1

  if [[ -z "$POD_NAME" ]]; then
    usage
    exit 1
  fi

  kubectl get po "$POD_NAME" -o json | jq ".status.containerStatuses[0].ready"
}

main "$@"
